apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-oidc-cluster-role-binding
subjects:
- kind: User
  name: github-oidc-auth-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: github-oidc-cluster-role
  apiGroup: rbac.authorization.k8s.io
