---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: smart-dhaka-namespace
  name: map-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map
  template:
    metadata:
      labels:
        app: map
    spec:
      containers:
        - name: map
          image: 038462776135.dkr.ecr.ap-south-1.amazonaws.com/smart-dhaka/map:latest
          ports:
            - containerPort: 8002
          envFrom:
            - secretRef:
                name: map-service-app-settings
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: smart-dhaka-namespace
  name: map-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8002
      protocol: TCP
  selector:
    app: map
---
apiVersion: autoscaling/v1  
kind: HorizontalPodAutoscaler
metadata:
  namespace: smart-dhaka-namespace
  name: map-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: map-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 85 

