name: "Deploy to K8S"
description: "Deploy to K8S"

inputs:
  SERVICE_NAME:
    description: SERVICE_NAME i.e. payment-deployment
    required: true
  DEPLOYMENT_NAME:
    description: DEPLOYMENT_NAME i.e. payment-deployment
    required: true
  AWS_REGION:
    description: AWS_REGION i.e. ap-south-1
    required: true
  AWS_ACCESS_KEY_ID:
    description: AWS_ACCESS_KEY_ID
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: AWS_SECRET_ACCESS_KEY
    required: true

  ECR_REPOSITORY_URL:
    description: ECR_REPOSITORY URL
    required: true
  VERSION:
    description: Image tag/version
    required: true
  REPOSITORY:
    description: "Remote repository name"
    required: true


  K8S_CLUSTER_NAME:
    description: Cluster to be deployed to
    required: true
  K8S_NAMESPACE:
    description: Namespace to be deployed
    required: true
  K8S_MANIFEST_FILE:
    description: K8S_MANIFEST_FILE to use
    required: true


runs:
  using: "composite"
  steps:

    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_REGION }}

    - name: Create EKS Credential
      shell: bash
      run: |
        aws eks --region  ${{ inputs.AWS_REGION }} update-kubeconfig --name ${{inputs.K8S_CLUSTER_NAME}}

    - name: Deploy to kubernetes
      shell: bash
      run: |
        cat ${{inputs.K8S_MANIFEST_FILE}} | sed "s|#{VERSION}#|${{inputs.VERSION}}|g;s|#{REPOSITORY}#|${{inputs.REPOSITORY}}|g;s|#{ECR_REPOSITORY_URL}#|${{inputs.ECR_REPOSITORY_URL}}|g" | kubectl -n ${{inputs.K8S_NAMESPACE}} apply -f -

    - name: Wait for rollout to finish
      shell: bash
      run: |
        kubectl -n ${{ inputs.K8S_NAMESPACE }} rollout restart deployment ${{ inputs.DEPLOYMENT_NAME }}